apiVersion: v1
kind: ConfigMap
metadata:
  name: neural-babel-config
  namespace: default
data:
  # Service endpoints (using KServe InferenceService URLs)
  asr_service_endpoint: "http://kube-whisperer.default.74.224.102.71.nip.io"
  translation_service_endpoint: "http://lexi-shift.default.74.224.102.71.nip.io"
  tts_service_endpoint: "http://vox-raga.default.74.224.102.71.nip.io"
  
  # Default settings
  default_source_lang: "en"
  default_target_lang: "fr"
  log_level: "INFO"
  supported_language_pairs: |
    en-fr
    en-de
    en-hi
    fr-en
    de-en
    hi-en 