apiVersion: apps/v1
kind: Deployment
metadata:
  name: neural-babel
  namespace: default
  labels:
    app: neural-babel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neural-babel
  template:
    metadata:
      labels:
        app: neural-babel
    spec:
      containers:
      - name: neural-babel
        image: bnracr.azurecr.io/neural-babel:0.0.1 
        imagePullPolicy: IfNotPresent
        env:
        - name: ASR_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: neural-babel-config
              key: asr_service_endpoint
        - name: TRANSLATION_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: neural-babel-config
              key: translation_service_endpoint
        - name: TTS_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: neural-babel-config
              key: tts_service_endpoint
        - name: DEFAULT_SOURCE_LANG
          valueFrom:
            configMapKeyRef:
              name: neural-babel-config
              key: default_source_lang
        - name: DEFAULT_TARGET_LANG
          valueFrom:
            configMapKeyRef:
              name: neural-babel-config
              key: default_target_lang
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: neural-babel-config
              key: log_level
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      imagePullSecrets:
      - name: acr-secret
      volumes:
      - name: config-volume
        configMap:
          name: neural-babel-config 
